### PR TITLE
Added Login and Registration Pages.

### LINKED ISSUE #3: Login and Registration
- Design UI of login and registration pages and implement them

### PR DESCRIPTION
**Pull request by jaimemiranda1**
- Added Login and Registration UI and its implementation

### CODE REVIEW

**Comment by joeyrhp** [comment]
This is just the UI for the login and register views right? The user cant actually create an account and log in?

**Comment by jaimemiranda1** [comment]
> This is just the UI for the login and register views right? The user cant actually create an account and log in?

Yes, just the UI. User can write on the text boxes, but the Login and Registration buttons don't do anything at the moment.

**Comment by joeyrhp** [comment]
> > This is just the UI for the login and register views right? The user cant actually create an account and log in?
> 
> Yes, just the UI. User can write on the text boxes, but the Login button and Registration buttons don't do anything at the moment.

Let's have a team discussion at tomorrows meeting for further steps and team insight, might be good that the code to be merged in this issue allows the user to register and/or login as well. The UI looks good though, nice job!

**Comment by jaimemiranda1** [comment]
> > > This is just the UI for the login and register views right? The user cant actually create an account and log in?
> > 
> > 
> > Yes, just the UI. User can write on the text boxes, but the Login button and Registration buttons don't do anything at the moment.
> 
> Let's have a team discussion at tomorrows meeting for further steps and team insight, might be good that the code to be merged in this issue allows the user to register and/or login as well. The UI looks good though, nice job!

Sounds good. Appreciate the feedback.

**Comment by jaimemiranda1** [comment]
Backend connected to Frontend. Code can now be merged after review.

**Review by joeyrhp — APPROVED** [review]

**Pull request merged**
